emit-tool-contracts:
	python -m pbcommand.cli.examples.dev_scatter_fasta_app --emit-tool-contract > dev_scatter_fasta_app_tool_contract.json 
	python -m pbcommand.cli.examples.dev_scatter_fasta_app --emit-tool-contract > dev_scatter_fasta_app_tool_contract.json
	python -m pbcommand.cli.examples.dev_quick_hello_world emit-tool-contracts
